### ISSUE TITLE
Glyph between "{0,0," and any number is missing in dot-line font

### ISSUE THREAD

**Issue by mklein994** [aftertheflood/sparks#17]
There seems to be a rendering error when using `{0,0,` and then any number. It just shows a comma instead of a dot. Here's a [codepen example](https://codepen.io/anon/pen/ZvvEyN?editors=1100):

![screenshot-2018-1-7 spark dot-line issue](https://user-images.githubusercontent.com/3069239/34654793-194b0c6e-f3c6-11e7-9362-d1f9795eb4db.png)

The problem shows up specifically in this order: a left brace, then 2 zeros with commas; it's fine every other time 2 zeros show up.

P. S.
Great work!

**Comment by ghost** [comment]
Hi there,

Thanks very much for raising this issue. I can confirm there is a bug when you have two zeros at the beginning of the braces. We will push a fix with our next update.

Thanks again and good luck with your project.

Best wishes,
Sabih

**Comment by michaelgallagher** [comment]
@mklein994 – that should be fixed now!

**Comment by mklein994** [comment]
It was for a moment in 8da2f789… then it was reverted in 3433272b.

**Comment by michaelgallagher** [comment]
Aaaand that would be me pulling an idiotic git move. Should be fixed now. Actually. I think.
