### ISSUE TITLE
Provide some examples

### ISSUE THREAD

**Issue by enko** [aftertheflood/sparks#2]
Please provide some examples with images how your sparklines look like. Also placing a link to [wikipedia](https://en.wikipedia.org/wiki/Sparkline) wouldn't hurt either. I did not know what sparklines are and your readme does not lift this confusion.

**Comment by dmnkhhn** [comment]
http://aftertheflood.co/projects/atf-spark

**Comment by riccardoerra** [comment]
Simple playground: https://codepen.io/riccardoerra/pen/ZXGvxE
