### ISSUE TITLE
Add gif/image to README and link to site

### ISSUE THREAD

**Issue by balzss** [aftertheflood/sparks#21]
Thanks for the awesome project!

I think the majority of the people who first stumble upon this font are interested in seeing it before reading about it. When I opened the repo I scanned the README for demo images and when I didn't find any I wanted to check out the site but there wasn't any link in the top of the repo (where they usually are).

Because there already are demo images in the site, adding it to the readme (and also the website link to the top of the repo) would take less than a minute.

Thanks

**Comment by ghost** [comment]
What a great idea, done!

Thanks for the suggestion.
