### ISSUE TITLE
Rendering numbers with decimals

### ISSUE THREAD

**Issue by mkinzo** [aftertheflood/sparks#23]
Using Illustrator 2018, I have a set of numbers with decimals. {33.6,35.7,37.4}

Instead of creating the graph, it creates a small square where the decimal is, and a dot for the number that is after the decimal. Did I miss something or is it just the font limitation? Thanks!

<img width="735" alt="screen shot 2018-06-25 at 3 34 54 pm" src="https://user-images.githubusercontent.com/40579072/41871569-57ed2dde-788d-11e8-8b96-15dec418b444.png">

**Comment by ghost** [comment]
Hi,

I am afraid that Sparks only renders whole numbers from 0 - 100 and does not currently support decimal places. The example on the readme is using decimal numbers outside of the rendered braces.

Hope this helps.
