### ISSUE TITLE
line-medium broken on web pages

### ISSUE THREAD

**Issue by nilslockean** [aftertheflood/sparks#5]
Every other font seems to be working beautifully but for some reason .spark-line-medium breaks (see screenshot).

![spark-line-medium-screenshot](https://user-images.githubusercontent.com/7281733/30369706-b0ffe9b4-9875-11e7-9e2f-53111d3d8eb2.png)

CSS:
`.spark-line-medium {
    font-family: "spark-line-medium";
    letter-spacing: 0em;
}`

**Comment by michaelgallagher** [comment]
That's because the dot-line version only goes from 0–9 for the moment. The plan is to expand the line version to support 0–100, but that hasn't happened yet. 

If you change the number series to something like {1,2,3,4,5,6,7,8,9} it should work fine.

**Comment by nilslockean** [comment]
Thank you, Michael!
