### ISSUE TITLE
Does work in Word 2010

### ISSUE THREAD

**Issue by eteichm** [aftertheflood/sparks#7]
Thanks for the great tool!
I tried using AtF Spark in Word 2010 after turning on contextual alternates: it doesn't work.
In the readme, I've noted that it works in Word 2011.
Is the fact that it's not working in Word 2010 related to Word 2010 or to the current definition of the font?

**Comment by michaelgallagher** [comment]
I'm fairly certain contextual alternates don't work in Word 2010 and that the ability to use them was added in the 2011 edition.

**Comment by eteichm** [comment]
Well, contextual alternates DO work in Word 2010!  
In Font > Advanced, you have to set : 
Kerning for fonts: 8 
Activate Use Contextual Alternates. 

Thanks to Jess at http://www.magpiepaperworks.com/blog/using-opentype-fonts-in-microsoft-word/ !
Pay attention: Any auto-correct functions (capitalizing the first letter of a sentence, automatic carriage returns, etc.) will override the font’s Opentype code. You may have to turn these functions off in Options/Preferences.

**Comment by michaelgallagher** [comment]
Oh! I stand corrected! 
@eteichm : if you turn that on does Spark work for you in Word 2010? (guessing not)

**Comment by eteichm** [comment]
Yes, Spark DOES work for me in Word 2010. 
I've changed the issue title accordingly. 
I suggest that you change the Readme.
I may be helpful to define new Word Styles with all the required settings. Well not really because a style applies to a full paragraph and not part of a sentence.
