### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by eclipseo** [aftertheflood/sparks#8]
I might be interested in packaging this for my Linux distribution, but I'm not sure under what license I am allowed to redistribute it? "Free to use and modify" is a bit vague.

**Comment by ghost** [comment]
hi eclipseo, thanks for pointing that out. I have now added a MIT License to our repo and linked it accordingly. Please feel free to package it in your Linux distribution and share the results with us, we would be really interested to see it when it's ready.

**Comment by eclipseo** [comment]
Perfect, I'll get back to you when I have the time to package it.

**Comment by eclipseo** [comment]
Would you mind too:
 
- adding the license to the fonts metadata
- making a Github release for Version 1

Thanks
